proxy_test.go

This actually already "works", but I wanted to have a test to ensure that.

proxy_test: add test to ensure Expect: 100-continue support works.

---

cmd/proxy/main.go

Respond with 404 to any unhandled internal request.

---

cmd/proxy/main.go
httpspec/httpspec.go
httpspec/httpspec_test.go

httpspec: add preconfigured stack for HTTP spec compliant proxy

---

martianhttp/martianhttp.go
martianhttp/martianhttp_test.go

martianhttp: add endpoint to retrieve current configuration.

---

proxy.go
proxy_test.go

This change allows HTTP messages to be sent through a connect tunnel, while a MITM config is setup. 
Without this change, the HTTP message is parsed as a TLS client hello, which is obviously not going to work.

Allow HTTP messages through CONNECT tunnel, if a MITM config is set.

---

proxy.go
proxy_test.go

Requests to servers which close the connection first currently hang when sent through a connect tunnel.

Fixes hanging connections when server closes first through connect tunnel.

---

har/har_handlers.go

This one empty line is important to the federation for reasons

whitespace: the final frontier

---

cmd/proxy/main.go
har/har.go
har/har_handlers.go
har/har_handlers_test.go
har/har_test.go

This reverts commit d0cf4d3dc21965c731551c3d0a98c6808fd5f4cd.

Revert "Updates to HAR and har_handlers"

---

cmd/proxy/main.go
har/har.go
har/har_handlers.go
har/har_handlers_test.go
har/har_test.go

LogResponse() =>  RecordResponse

---

web/elements/om-message-list/om-message-list.html
web/elements/om-message-list/parse-log.js
web/scripts/frame-reader.js

Unlock latent semi-broken logic by unhiding the upload button and fixing the logic to no longer be broken.

Adding the ability to upload marbl log files

---

web/elements/om-message-websocket/om-message-websocket.html

make this a relative path so it can be served from an arbitrary URL, not just root on a domain

change the script import to a relative url

---

cmd/proxy/main.go

Forward API requests before httpspec modifiers are applied to avoid the addition of the via header.  The via header is tripping loop detection for API requests that are forwarded from the traffic port ot the api port.

Forward API requests before httpspec modifiers

---

header/header_value_regex_filter.go

adding a header regex filter

---

har/har.go

This unties the logic for http.{Request,Response} -> har.{Request,Response} conversion from the har.Logger, so that logic can be used separately from the Logger.

har: Split NewRequest/Response functions out of RecordRequest/Response

---

cmd/proxy/main.go
cybervillains/cybervillains.go
mobileproxy/mobileproxy.go

add stash and static modifiers to mobile proxy
add the cybervillains cert and key to new cybervillains package

add stash and static modifiers to mobile proxy and add pkg cybervillains

---

mobileproxy/mobileproxy.go

Fixes funciton names in godocs

Fixes docs

---

static/static_file_modifier.go
static/static_file_modifier_test.go

Allow setting explicit paths via the JSON API.

---

web/scripts/frame-reader.js

not sure how this lived this way for so long

fix indentation

---

header/header_filter_test.go

In PR #137 , the tests were only on the matching cases. I added some statements for the else cases.

Testing the else condition for header filter.

---

context.go

Revert "Updating a request/response Context should lock mutex for read/writing."

---

context.go

Reverts google/martian#181
Reverts the revert of 180 - CLA is confirmed signed by @pytlesk4 
Thanks @pytlesk4 !

Revert "Revert "Updating a request/response Context should lock mutex for read/writing.""

---

cmd/proxy/main.go
cmd/proxy/main_test.go

Add an end to end test to exercise the proxy as standalone process.

Proxy end to end test

---

body/body_modifier.go
body/body_modifier_test.go

Single range request only supported
Multipart range requests not supported - will result in 416 status code

Range request header support in body.Modifier

---

body/body_modifier.go
body/body_modifier_test.go
cmd/proxy/main_test.go

- support for multipart range request in body.Modifier for response modification
- drive by refactoring of golint findings in main_test.go

Range request header support in body_modifier: add support for multipart range request

---

header/via_modifier.go
header/via_modifier_test.go
httpspec/httpspec_test.go

add random boundary characters to via header

---

har/har.go
har/har_test.go

har: use multiple Header values for multi-valued headers

---

proxy.go
proxy_test.go

Fixes #286.
It's not OK to call `Add` and `Wait` concurrently on a `sync.WaitGroup`. `Done` is OK to call whenever:
https://golang.org/pkg/sync/#WaitGroup.Add
Normally the fix would be to move the call to `Add` out of the goroutine (e.g., from inside `handleLoop` to `Serve` before `go handleLoop`). However, it appears that `Serve` itself is often called in a user goroutine, so that won't help here.
The test fails on `go test -count=1 -race --run TestRacyClose` without the fix.

fix race between proxy.Serve and Close

---

api/forwarder.go
api/forwarder_test.go
cmd/proxy/main.go

get port from bound socket instead of trying to parse it from addres
spec

fix --api-addr command line flag
