- examples/main.go
- header/forwarded_modifier.go
- header/forwarded_modifier_test.go
- header/framing_modifier.go
- header/framing_modifier_test.go
- header/hopbyhop_modifier.go
- header/hopbyhop_modifier_test.go
- header/via_modifier.go
- header/via_modifier_test.go
- martianhttp/martianhttp.go
- martianhttp/martianhttp_test.go
- mitm.go
- proxy.go
- proxy_test.go
- proxyutil/proxyutil.go
- proxyutil/proxyutil_test.go
HTTP proxies are required to implement certain functionality as per the
spec. However, some customers want to use Martian more as a transparent
proxy and would rather it not manipulate the request/response at all if
possible.
I have moved some of the core functionality such as checking for bad
framing and the removal of hop-by-hop headers to modifiers that will be
recommended, but not required.
> Move spec proxy behavior to optional modifiers.

- examples/main.go
- log.go
- proxy.go
- proxy_test.go
- response_writer.go
- response_writer_test.go
This allows end users to easily configure Martian through Martian as
well as support heartbeats and other functionality.
> proxy: Add in-proxy ServeMux.

- cookie/cookie_modifier.go
- examples/main.go
- log/log.go
- log/log_test.go
- martianhttp/martianhttp.go
- martianlog/logger.go
- martianlog/logger_test.go
- martiantest/martiantest.go
- mitm/mitm.go
- noop.go
- proxy.go
- verify/verify_handlers.go
The motivation for this change is to allow logging to be controlled from
a central package that won't ever cause cyclic dependencies. This was a
problem when attempting to use the logging functions in the mitm package
since the martian package depends on mitm.
> log: separate logging from martian package.

- martianlog/logger.go
- martianlog/logger_test.go
- messageview/messageview.go
- messageview/messageview_test.go
Additionally, move the decode option to the reader itself rather than the MessageView. Allows a single MessageView to be read for both the decoded message for logging and as an exact copy.
> messageview: move MessageView from proxyutil to its own package.

- README.md
- cmd/proxy/main.go
- har/har.go
- har/har_handlers.go
- har/har_handlers_test.go
- har/har_test.go
- messageview/messageview.go
Add a HAR logger to Martian. It is mostly to spec (or at least intends to be) except for three specific exceptions:
*  Entries can have a `request` without an accompanying `response`. This allows one to take a snapshot of the current logs even if the response hasn't come back yet (such as if it's taking too long).
*  `entry.time` is the delta between the last request modification and response modification, approximately the round trip time for the client. It does not reflect the sum of `timings.{send,wait,receive}`.
*  `timings` is semantically empty because we reuse http.RoundTripper and don't have access to those numbers, but the `send`, `wait`, and `receive` keys are required to be present so they are.
Fixes #32
> har: add HAR logging package and API

- README.md
Hi! I just installed the proxy via
go get github.com/google/martian/cmd/proxy
go install github.com/google/martian/cmd/proxy
and I tried to set the port via `proxy -port=9090`, but found:
bash-3.2$ proxy -port=9090
flag provided but not defined: -port
whereas using the `-addr` flag works as described in the help:
bash-3.2$ proxy -addr=:9090
2015/11/11 11:07:53 martian: proxy started on: [::]:9090
This pr just changes the incorrect line in the readme, assuming that the change was made without updating docs (and not that the docs represent an upcoming API change :P)
> README: update port example to use -addr flag

- README.md
I had some trouble getting started using `martian`, and then realized I needed to `go get` it first, instead of cloning it via git.
> clarify install instructions

- cmd/proxy/main.go
- mitm/mitm.go
- mitm/mitm_test.go
@brunoqc We should have support for transparent MITM on TLS in the library, but I don't think it ever got added to the cmd/proxy. Mind giving this branch a try and letting me know if it works for your use case?
> cmd/proxy: add support for transparent TLS MITM listener.

- messageview/messageview.go
- messageview/messageview_test.go
We were incorrectly printing the Content-Length if Transfer-Encoding is not chunked without checking that there was, in fact, a valid Content-Length. Seeing tests fail trying to parse an invalid, negative, Content-Length header.
> messageview: fix bug for messages missing Content-Length and Transfer-Encoding

- proxy.go
- proxy_test.go
Peek the connection to determine type of data on a CONNECT tunnel, rather than assuming based on the port of the connect request. 
Added test to verify this is working with multiple requests on the same connection.
> Peek the connection to determine type of data on a CONNECT tunnel

- proxy.go
Currently error messages from Flush and Write are disregarded when errors are likely evidence of something being wrong. This change adds logging in these cases.
> Add extra logging when a response has issues being written back to the client.

- web/elements/om-message-list/om-message-list.html
- web/elements/om-message/om-message.html
- web/elements/om-messages-stream/om-messages-stream.html
- web/test/elements/om-message-list_test.html
- web/test/elements/om-message_test.html
added timestamp display when its being logged by the martian, and fixed a bug that sometimes caused response code and latency not to render (which was required some real fighting of polymer, which makes false assumptions about whether things have changed)
> display response latency in olympus mons (when martian sends timestamps)

- .travis.yml
- proxy_test.go
I don't know why this assertion is causing the test to hang.  Opening a bug for it.
> Getting the build green by commenting out the error assertion in TestIntegrationTLSHandshakeErrorCallback

- web/elements/om-message-list/om-message-list.html
- web/elements/om-message-list/parse-log.js
- web/elements/om-message-websocket/om-message-websocket.html
When you import via Worker(), the url of the .js needs to be relative to the top level HTML file being loaded.
When you import via importScripts or <script src="">, the url needs to be relative to the enclosing file.
Also cleaned up some duplication and debug logging
> fix URLs of js imports 

- mobileproxy/mobileproxy.go
- proxy.go
Had to stop using the default serve mux to support at least unit testing stopping and starting of martian on mobile.  This is probably useful for real shutdown/restarts as well.
This also no longer waits for open connections to close when calling Close() on the proxy. Previously, this would wait for several minutes every time due to persistent connections.
> Get state of martian on mobile & support restarting martian.

- querystring/query_string_filter.go
- querystring/query_string_filter_test.go
- querystring/query_string_matcher.go
Previously the query string filter had its own matcher implementation. New merging with the newly created matcher in PR #137.
> Building query_string filter

- header/header_filter.go
- header/header_filter_test.go
Previously martian will crash when the header filter does not have "else" field in it:
For example: 
>  header_filter_test.go:133: parse.FromJSON(): got unexpected end of JSON input, want no error
On: 
```
{                                                                                                                                                                                         
"header.Filter": {                                                                                                                                                                                   
"scope": ["request", "response"],                                                                                                                                                                
"name": …
```
> Fixing header filter when no else modifiers present in the JSON request

- mobile/init.go
This was accidentally moved here, it should *only* live in the non-mobile init.go.
> There are no flags in the mobile interface.

- cmd/proxy/main.go
- mobile/proxy.go
- mobileproxy/mobileproxy.go
Requests that match patterns in mux are requests to the proxy API, and they should not be logged
> do not log requests that match patterns in mux

- cmd/proxy/main.go
- cmd/proxy/main_test.go
- proxy.go
The -skip-tls-verify flag did not apply to the proxy's outbound connection. This change fixes that issue with an accompanying https integration test.
Also refactored the test.
> Make -skip-tls-verify apply to proxy outbound connection

- cmd/proxy/main.go
- failure/failure_verifier.go
- failure/failure_verifier_test.go
- mobile/proxy.go
This is a verifier that you can initialize with an error message, and will fail for any request that hits it. By wrapping it in a filter, you can effectively turn any filter into verifier that will log an error to /verify.
> Added failure verifier.

- cmd/proxy/main.go
- mobile/proxy.go
since ListenAndServeTLS requires the path the the cert and key files, this change writes the cert and key to a temp directory.
> mobile/proxy API can be served over TLS 

- marbl/marbl.go
- marbl/marbl_test.go
When writing data frame based on Read() call we need to write only bytes that were actually filled by Read(). Before we were wirting the whole slice as data even if Read() filled only few bytes in the slice.
> Fix bug in marbl data frame writing.

- mobile/proxy.go
Under iOS/OS X binding all interfaces pops up a prompt
> add mobile martian option for loopback only listener

- mobile/proxy.go
Martian.Shutdown() does not actually shut down all of the listening sockets that Start() binds
> fix martian/mobile shutdown leaving API socket

- har/har.go
- har/har_handlers.go
- har/har_handlers_test.go
- har/har_test.go
Currently there's no way to tail the martian logs (except with the MARBL WebSocket endpoint), which limits the use of Martian for long running tests that move lots of data over HTTP.
The `GET /logs` && `DELETE /logs/reset` functionality comes close, but is not atomic, discards responses to in flight requests from the log and scales `O(n*log(n))` with the batch size due to a sort.
This PR:
- Links `Entry` structs into a list that maintains insertion order which removes the need for sorting
- Adds a `?return=1` option to the reset endpoint that returns the completed request/response pairs, leaving behind all in flight requests.
- Preserves the normal functionality of the reset endpoint (all requests are purged including requests without responses).
> add reset and export functionality to HAR logs

- nosigpipe/nosigpipe.go
- nosigpipe/nosigpipe_darwin.go
- proxy.go
When doing iOS development a SIGPIPE pauses Xcode whenever Martian attempts to write to a socket after an HTTP client has hung-up.
golang 1.9 introduces a new mechanism for accessing the underlying file descriptors, which allows us to set `SO_NOSIGPIPE` on the socket.
> suppress SIGPIPE on Darwin

- marbl/marbl.go
- marbl/marbl_test.go
Currently the `:path` and `:query` MARBL headers come back inconsistently with the query URL-encoded and the path decoded.
`http://example.com/foo%20bar?baz%20qux` turns into `:path: /foo bar` and `:query: baz%20qux`
`http://example.com/foo%20bar?baz%20qux` turns into `:path: /foo%20bar` and `:query: baz%20qux`
> encode MARBL url-component pseudo-headers consistently

- CONTRIBUTING
Hi. I use Google services frequently.
I'm a favorite company and I hope to contribute to Google. This time, I will send you PR because I found a point that I can correct about the notation of `Github`.
Other projects use the notation `GitHub`, but this project was fixed as` Github`
thank you.
> Other projects use the notation GitHub, but this project was fixed as Github.

- .travis.yml
- README.md
[sort.SliceStable](https://github.com/google/martian/blob/a0d62b8f5af8847d8f523c33f45e509b390383f1/trafficshape/utils.go#L183) and [http.ServeTLS](https://github.com/google/martian/blob/a0d62b8f5af8847d8f523c33f45e509b390383f1/mobile/proxy.go#L249) are go 1.8 only.
The former can be solved with:
```
-               sort.SliceStable(shape.Throttles, func(i, j int) bool {
-                       return shape.Throttles[i].ByteStart < shape.Throttles[j].ByteStart
-                       })
+               sort.Sort(ByByteStart(shape.Throttles))
defaultBandwidth := DefaultBitrate / 8
if shape.MaxBandwidth > 0 {
@@ -196,8 +194,19 @@ func parseShapes(ts *Trafficshape) error {
shape.Actions = append(shape.Actions, throttleActions...)
// Sort the actions according to their byte offset.
- …
```
> bump required version of go

- har/har.go
- har/har_test.go
Previously, it was string, which doesn't correctly round-trip with
encoding/json because that package requires strings to be valid UTF-8.
The right type is []byte, since post data can be arbitrary bytes.
Fixes #245.
> har: change PostData.Text to []byte

- messageview/messageview.go
- messageview/messageview_test.go
When decoding a response body, if the status indicates partial (or no) content,
don't attempt to decompress the body.
Fixes #254.
> do not decompress partial content

- marbl/handler.go
- marbl/handler_test.go
Currently the MARBL endpoint spins up a goroutine per sent frame, per websocket connection (!) which not only is effectively a hidden infinite buffer, but breaks the ordering of the MARBL frames making it impossible to know when all frames for a particular req/rep have been received.
This:
- Adds a huge buffer per WS frame channel
- Hangs up when the buffer is filled
- Makes additions to the buffer occur on the writing goroutine
> fix MARBL websocket endpoint frames coming back in arbitrary order

- marbl/handler.go
- marbl/handler_test.go
Fix for issue #282.  The flake was caused by a race condition between subscribing the frame channel during websocket connection creation and the first write happening.  The test starts writing to the handler as soon as the websocket is connected, but there is a delay between the websocket being created and when a channel is created and subscribed.  If writes happen before the channel is subscribed, those writes don't get propagated to the websocket.  This should fail the test, but the test used t.Errorf(), which only records the failure and continues the test.  Because those initial writes were lost, the test ends up reading fewer messages than was sent and keeps waiting for more messages that will never arrive, thereby hanging the test.
The solution is to add a short sleep before the …
> Fix marbl test flake by adding a short sleep and failing fast.

- marbl/handler_test.go
occasionally the reg in the server isn't complete when writes start
> fix MARBL handler test flake

- .travis.yml
- proxy.go
- trafficshape/conn.go
- trafficshape/listener.go
- trafficshape/utils.go
Bug was cause by a type assertion against *tls.Conn which was always going to be false for connections that are *trafficshape.Conn
Added functionality to expose the underlying Conn of a trafficshape.Conn so that we can correctly mark the conn as secure if the underlying conn is a tls.Conn.
Moved trafficshape.Conn into trafficshape/conn.go
Refactored handleLoop in proxy.go a bit by pulling out handleConnectRequest and readRequest
Updated travis.yml to go 1.11
> fix issue with trafficshaping incorrectly downgrading TLS requests

- method/method_filter.go
Advantages -
1. Efficient and more optimal in all cases, refer [https://www.digitalocean.com/community/questions/how-to-efficiently-compare-strings-in-go](url) for benchmarks.
2. More readable code.
3. Still uses the standard library.
> Using strings.EualFold() for efficient string comparison

- cmd/proxy/main.go
ctrl+c was not able to kill the server, now after pressing ctrl+x the server exits with 0 code.
> Enable ctrl+c to kill the server

- cmd/proxy/main.go
user namespace program is not able to catch the real kill signal(kill -9)
> Remove listen signal kill (kill -9)

- proxy.go
- proxy_test.go
I would like to be able to wrap the RoundTripper from a proxy and this change simply exports the field.
If there is a preference to use a method like proxy.GetRoundTripper instead of exporting then I'm more than happy to switch to that style of an implementation.
> Export proxy.RoundTripper

- har/har.go
- har/har_test.go
The use of `[]byte` for the `har.Content.Text` field means that go's
json library will always interpret the field as base64 encoded.
The current implementation works out because this library only
generates Content with base64 encoding, and users effectively assume
the `har.Content.Text` field always contains decoded data.
However, this doesn't work if using this library to load a HAR file
generated by another source (i.e. chrome). To address this, this PR:
1. Makes it explicit that the `Text` field only contains decoded data
2. Adds custom JSON marshaler/unmarshaler to automatically encode/decode
data based on the `Encoding` field.
> Handle non-base64 encoded har.Content.Text

- proxy.go
Do not print errors for listener closing
> Handle listener closed error gracefully

- log/log.go
When martian is used as package, it needs to work along with the host's
logging infrastructure. This change adds support for custom logging.
By default, it retains current logging, provides an option to change the logger if needed.
> Support customer logger
